name: SecuroScan
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^6.0.0
  http: ^0.13.6
  url_launcher: ^6.2.6
  network_info_plus: ^4.0.3
  #file_picker: ^6.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - api.env  # ✅ add this line
